### ISSUE TITLE
NER dataset

### ISSUE THREAD

**Issue by harpap** [macocu/LanguageModels#1]
Hello! I was looking at your repo and your [huggingface model for turkish](https://huggingface.co/MaCoCu/XLMR-MaCoCu-tr) since I am intersted in a NER model for this language for research purposes. 
I couldn't obtain how the NER training was performed and, also, I realised that the dataset that you mention is not annotated for NER. Can you point me to the right direction to replicate the results mentioned here?
![image](https://user-images.githubusercontent.com/10978002/224707237-a8ca1134-0143-45db-9812-565ddfd96ae0.png)

Thanks in advance!

**Comment by RikVN** [comment]
Hi - I'm not entirely sure what the problem is, did you check the instructions here:

https://github.com/macocu/LanguageModels#fine-tuning-on-gpu

There you'll find instructions on how to download the data and then finetune a model on it. Let me know if you have any issues.

**Comment by harpap** [comment]
Yes you are right :)
I was hoping you used something other than wikiANN, since this dataset does not seem optimal and I can't find anything better.
thank you for this open repo, closing this issue...
